package util;

public enum ListaClasificaciones {
	
	SEASON20002001ESTE(2000,"ESTE",
			new ListaEquipos[] {ListaEquipos.PHILADELPHIA76ERS,ListaEquipos.MILWAUKEEBUCKS,ListaEquipos.MIAMIHEAT,ListaEquipos.NEWYORKKNICKS,
								ListaEquipos.TORONTORAPTORS,ListaEquipos.CHARLOTTEHORNETS,ListaEquipos.ORLANDOMAGIC,ListaEquipos.INDIANAPACERS,
								ListaEquipos.BOSTONCELTICS,ListaEquipos.DETROITPISTONS,ListaEquipos.CLEVELANDCAVALIERS,ListaEquipos.NEWJERSEYNETS,
								ListaEquipos.ATLANTAHAWKS,ListaEquipos.WASHINGTONWIZARDS,ListaEquipos.CHICAGOBULLS}),
	SEASON20002001OESTE(2000,"OESTE",
			new ListaEquipos[] {ListaEquipos.SANANTONIOSPURS,ListaEquipos.LOSANGELESLAKERS,ListaEquipos.SACRAMENTOKINGS,ListaEquipos.UTAHJAZZ,
								ListaEquipos.DALLASMAVERICKS,ListaEquipos.PHOENIXSUNS,ListaEquipos.PORTLANDTRAILBLAZERS,ListaEquipos.MINNESOTATIMBERWOLVES,
								ListaEquipos.HOUSTONROCKETS,ListaEquipos.SEATTLESUPERSONICS,ListaEquipos.DENVERNUGGETS,ListaEquipos.LOSANGELESCLIPPERS,
								ListaEquipos.VANCOUVERGRIZZLIES,ListaEquipos.GOLDENSTATEWARRIORS}),
	
	SEASON20012002ESTE(2001,"ESTE",
			new ListaEquipos[] {ListaEquipos.NEWJERSEYNETS,ListaEquipos.DETROITPISTONS,ListaEquipos.BOSTONCELTICS,ListaEquipos.CHARLOTTEHORNETS,
								ListaEquipos.ORLANDOMAGIC,ListaEquipos.PHILADELPHIA76ERS,ListaEquipos.TORONTORAPTORS,ListaEquipos.INDIANAPACERS,
								ListaEquipos.MILWAUKEEBUCKS,ListaEquipos.WASHINGTONWIZARDS,ListaEquipos.MIAMIHEAT,ListaEquipos.ATLANTAHAWKS,
								ListaEquipos.NEWYORKKNICKS,ListaEquipos.CLEVELANDCAVALIERS,ListaEquipos.CHICAGOBULLS}),
	
	SEASON20012002OESTE(2001,"OESTE",
			new ListaEquipos[] {ListaEquipos.SACRAMENTOKINGS,ListaEquipos.SANANTONIOSPURS,ListaEquipos.LOSANGELESLAKERS,ListaEquipos.DALLASMAVERICKS,
								ListaEquipos.MINNESOTATIMBERWOLVES,ListaEquipos.PORTLANDTRAILBLAZERS,ListaEquipos.SEATTLESUPERSONICS,ListaEquipos.UTAHJAZZ,
								ListaEquipos.LOSANGELESCLIPPERS,ListaEquipos.PHOENIXSUNS,ListaEquipos.HOUSTONROCKETS,ListaEquipos.DENVERNUGGETS,
								ListaEquipos.MEMPHISGRIZZLIES,ListaEquipos.GOLDENSTATEWARRIORS}),
	
	SEASON20022003ESTE(2002,"ESTE",
			new ListaEquipos[] {ListaEquipos.DETROITPISTONS,ListaEquipos.NEWJERSEYNETS,ListaEquipos.INDIANAPACERS,ListaEquipos.PHILADELPHIA76ERS,
								ListaEquipos.CHARLOTTEHORNETS,ListaEquipos.BOSTONCELTICS,ListaEquipos.MILWAUKEEBUCKS,ListaEquipos.ORLANDOMAGIC,
								ListaEquipos.NEWYORKKNICKS,ListaEquipos.WASHINGTONWIZARDS,ListaEquipos.ATLANTAHAWKS,ListaEquipos.CHICAGOBULLS,
								ListaEquipos.MIAMIHEAT,ListaEquipos.TORONTORAPTORS,ListaEquipos.CLEVELANDCAVALIERS}),
	
	
	SEASON20022003OESTE(2002,"OESTE",
			new ListaEquipos[] {ListaEquipos.SANANTONIOSPURS,ListaEquipos.SACRAMENTOKINGS,ListaEquipos.DALLASMAVERICKS,ListaEquipos.MINNESOTATIMBERWOLVES,
								ListaEquipos.LOSANGELESLAKERS,ListaEquipos.PORTLANDTRAILBLAZERS,ListaEquipos.UTAHJAZZ,ListaEquipos.PHOENIXSUNS,ListaEquipos.HOUSTONROCKETS,
								ListaEquipos.SEATTLESUPERSONICS,ListaEquipos.GOLDENSTATEWARRIORS,ListaEquipos.MEMPHISGRIZZLIES,ListaEquipos.LOSANGELESCLIPPERS,
								ListaEquipos.DENVERNUGGETS}),
	
	
	SEASON20032004ESTE(2003,"ESTE",
			new ListaEquipos[] {ListaEquipos.INDIANAPACERS,ListaEquipos.NEWJERSEYNETS,ListaEquipos.DETROITPISTONS,ListaEquipos.MIAMIHEAT,ListaEquipos.NEWORLEANSHORNETS,
								ListaEquipos.MILWAUKEEBUCKS,ListaEquipos.NEWYORKKNICKS,ListaEquipos.BOSTONCELTICS,ListaEquipos.CLEVELANDCAVALIERS,ListaEquipos.TORONTORAPTORS,
								ListaEquipos.PHILADELPHIA76ERS,ListaEquipos.ATLANTAHAWKS,ListaEquipos.WASHINGTONWIZARDS,ListaEquipos.CHICAGOBULLS,ListaEquipos.ORLANDOMAGIC}),
	
	
	SEASON20032004OESTE(2003,"OESTE",
			new ListaEquipos[] {ListaEquipos.MINNESOTATIMBERWOLVES,ListaEquipos.LOSANGELESLAKERS,ListaEquipos.SANANTONIOSPURS,ListaEquipos.SACRAMENTOKINGS,ListaEquipos.DALLASMAVERICKS,
								ListaEquipos.MEMPHISGRIZZLIES,ListaEquipos.HOUSTONROCKETS,ListaEquipos.DENVERNUGGETS,ListaEquipos.UTAHJAZZ,ListaEquipos.PORTLANDTRAILBLAZERS,
								ListaEquipos.GOLDENSTATEWARRIORS,ListaEquipos.SEATTLESUPERSONICS,ListaEquipos.PHOENIXSUNS,ListaEquipos.LOSANGELESCLIPPERS}),
	
	
	SEASON20042005ESTE(2004,"ESTE",
			new ListaEquipos[] {ListaEquipos.MIAMIHEAT,ListaEquipos.DETROITPISTONS,ListaEquipos.BOSTONCELTICS,ListaEquipos.CHICAGOBULLS,ListaEquipos.WASHINGTONWIZARDS,
								ListaEquipos.INDIANAPACERS,ListaEquipos.PHILADELPHIA76ERS,ListaEquipos.NEWJERSEYNETS,ListaEquipos.CLEVELANDCAVALIERS,ListaEquipos.ORLANDOMAGIC,
								ListaEquipos.TORONTORAPTORS,ListaEquipos.NEWYORKKNICKS,ListaEquipos.MILWAUKEEBUCKS,ListaEquipos.CHARLOTTEBOBCATS,ListaEquipos.ATLANTAHAWKS}),
	
	
	SEASON20042005OESTE(2004,"OESTE",
			new ListaEquipos[] {ListaEquipos.PHOENIXSUNS,ListaEquipos.SANANTONIOSPURS,ListaEquipos.SEATTLESUPERSONICS,ListaEquipos.DALLASMAVERICKS,ListaEquipos.HOUSTONROCKETS,
								ListaEquipos.SACRAMENTOKINGS,ListaEquipos.DENVERNUGGETS,ListaEquipos.MEMPHISGRIZZLIES,ListaEquipos.MINNESOTATIMBERWOLVES,ListaEquipos.LOSANGELESCLIPPERS,
								ListaEquipos.LOSANGELESLAKERS,ListaEquipos.GOLDENSTATEWARRIORS,ListaEquipos.PORTLANDTRAILBLAZERS,ListaEquipos.UTAHJAZZ,ListaEquipos.NEWORLEANSHORNETS}),
	
	
	SEASON20052006ESTE(2005,"ESTE",
			new ListaEquipos[] {ListaEquipos.DETROITPISTONS,ListaEquipos.MIAMIHEAT,ListaEquipos.NEWJERSEYNETS,ListaEquipos.CLEVELANDCAVALIERS,ListaEquipos.WASHINGTONWIZARDS,
								ListaEquipos.INDIANAPACERS,ListaEquipos.CHICAGOBULLS,ListaEquipos.MILWAUKEEBUCKS,ListaEquipos.PHILADELPHIA76ERS,ListaEquipos.ORLANDOMAGIC,
								ListaEquipos.BOSTONCELTICS,ListaEquipos.TORONTORAPTORS,ListaEquipos.CHARLOTTEBOBCATS,ListaEquipos.ATLANTAHAWKS,ListaEquipos.NEWYORKKNICKS}),
	
	
	SEASON20052006OESTE(2005,"OESTE",
			new ListaEquipos[] {ListaEquipos.SANANTONIOSPURS,ListaEquipos.PHOENIXSUNS,ListaEquipos.DENVERNUGGETS,ListaEquipos.DALLASMAVERICKS,ListaEquipos.MEMPHISGRIZZLIES,
								ListaEquipos.LOSANGELESCLIPPERS,ListaEquipos.LOSANGELESLAKERS,ListaEquipos.SACRAMENTOKINGS,ListaEquipos.UTAHJAZZ,ListaEquipos.NEWORLEANSOKLAHOMACITYHORNETS,
								ListaEquipos.SEATTLESUPERSONICS,ListaEquipos.HOUSTONROCKETS,ListaEquipos.GOLDENSTATEWARRIORS,ListaEquipos.MINNESOTATIMBERWOLVES,ListaEquipos.PORTLANDTRAILBLAZERS}),
	
	
	SEASON20062007ESTE(2006,"ESTE",
			new ListaEquipos[] {ListaEquipos.DETROITPISTONS,ListaEquipos.CLEVELANDCAVALIERS,ListaEquipos.TORONTORAPTORS,ListaEquipos.MIAMIHEAT,ListaEquipos.CHICAGOBULLS,
								ListaEquipos.NEWJERSEYNETS,ListaEquipos.WASHINGTONWIZARDS,ListaEquipos.ORLANDOMAGIC,ListaEquipos.INDIANAPACERS,ListaEquipos.PHILADELPHIA76ERS,
								ListaEquipos.CHARLOTTEBOBCATS,ListaEquipos.NEWYORKKNICKS,ListaEquipos.ATLANTAHAWKS,ListaEquipos.MILWAUKEEBUCKS,ListaEquipos.BOSTONCELTICS}),
	
	
	SEASON20062007OESTE(2006,"OESTE",
			new ListaEquipos[] {ListaEquipos.DALLASMAVERICKS,ListaEquipos.PHOENIXSUNS,ListaEquipos.SANANTONIOSPURS,ListaEquipos.UTAHJAZZ,ListaEquipos.HOUSTONROCKETS,
								ListaEquipos.DENVERNUGGETS,ListaEquipos.LOSANGELESLAKERS,ListaEquipos.GOLDENSTATEWARRIORS,ListaEquipos.LOSANGELESCLIPPERS,ListaEquipos.NEWORLEANSOKLAHOMACITYHORNETS,
								ListaEquipos.SACRAMENTOKINGS,ListaEquipos.PORTLANDTRAILBLAZERS,ListaEquipos.MINNESOTATIMBERWOLVES,ListaEquipos.SEATTLESUPERSONICS,ListaEquipos.MEMPHISGRIZZLIES}),
	
	
	SEASON20072008ESTE(2007,"ESTE",
			new ListaEquipos[] {ListaEquipos.BOSTONCELTICS,ListaEquipos.DETROITPISTONS,ListaEquipos.ORLANDOMAGIC,ListaEquipos.CLEVELANDCAVALIERS,ListaEquipos.WASHINGTONWIZARDS,
								ListaEquipos.TORONTORAPTORS,ListaEquipos.PHILADELPHIA76ERS,ListaEquipos.ATLANTAHAWKS,ListaEquipos.INDIANAPACERS,ListaEquipos.NEWJERSEYNETS,
								ListaEquipos.CHICAGOBULLS,ListaEquipos.CHARLOTTEBOBCATS,ListaEquipos.MILWAUKEEBUCKS,ListaEquipos.NEWYORKKNICKS,ListaEquipos.MIAMIHEAT}),
	
	
	SEASON20072008OESTE(2007,"OESTE",
			new ListaEquipos[] {ListaEquipos.LOSANGELESLAKERS,ListaEquipos.NEWORLEANSHORNETS,ListaEquipos.SANANTONIOSPURS,ListaEquipos.UTAHJAZZ,ListaEquipos.HOUSTONROCKETS,
								ListaEquipos.PHOENIXSUNS,ListaEquipos.DALLASMAVERICKS,ListaEquipos.DENVERNUGGETS,ListaEquipos.GOLDENSTATEWARRIORS,ListaEquipos.PORTLANDTRAILBLAZERS,
								ListaEquipos.SACRAMENTOKINGS,ListaEquipos.LOSANGELESCLIPPERS,ListaEquipos.MINNESOTATIMBERWOLVES,ListaEquipos.MEMPHISGRIZZLIES,ListaEquipos.SEATTLESUPERSONICS}),
	
	
	SEASON20082009ESTE(2008,"ESTE",
			new ListaEquipos[] {ListaEquipos.CLEVELANDCAVALIERS,ListaEquipos.BOSTONCELTICS,ListaEquipos.ORLANDOMAGIC,ListaEquipos.ATLANTAHAWKS,ListaEquipos.MIAMIHEAT,
								ListaEquipos.PHILADELPHIA76ERS,ListaEquipos.CHICAGOBULLS,ListaEquipos.DETROITPISTONS,ListaEquipos.INDIANAPACERS,ListaEquipos.CHARLOTTEBOBCATS,
								ListaEquipos.NEWJERSEYNETS,ListaEquipos.MILWAUKEEBUCKS,ListaEquipos.TORONTORAPTORS,ListaEquipos.NEWYORKKNICKS,ListaEquipos.WASHINGTONWIZARDS}),
	
	
	SEASON20082009OESTE(2008,"OESTE",
			new ListaEquipos[] {ListaEquipos.LOSANGELESLAKERS,ListaEquipos.DENVERNUGGETS,ListaEquipos.SANANTONIOSPURS,ListaEquipos.PORTLANDTRAILBLAZERS,ListaEquipos.HOUSTONROCKETS,
								ListaEquipos.DALLASMAVERICKS,ListaEquipos.NEWORLEANSHORNETS,ListaEquipos.UTAHJAZZ,ListaEquipos.PHOENIXSUNS,ListaEquipos.GOLDENSTATEWARRIORS,
								ListaEquipos.MINNESOTATIMBERWOLVES,ListaEquipos.MEMPHISGRIZZLIES,ListaEquipos.OKLAHOMACITYTHUNDER,ListaEquipos.LOSANGELESCLIPPERS,ListaEquipos.SACRAMENTOKINGS}),
	
	
	SEASON20092010ESTE(2009,"ESTE",
			new ListaEquipos[] {ListaEquipos.CLEVELANDCAVALIERS,ListaEquipos.ORLANDOMAGIC,ListaEquipos.ATLANTAHAWKS,ListaEquipos.BOSTONCELTICS,ListaEquipos.MIAMIHEAT,
								ListaEquipos.MILWAUKEEBUCKS,ListaEquipos.CHARLOTTEBOBCATS,ListaEquipos.CHICAGOBULLS,ListaEquipos.TORONTORAPTORS,ListaEquipos.INDIANAPACERS,
								ListaEquipos.NEWYORKKNICKS,ListaEquipos.DETROITPISTONS,ListaEquipos.PHILADELPHIA76ERS,ListaEquipos.WASHINGTONWIZARDS,ListaEquipos.NEWJERSEYNETS}),
	
	
	SEASON20092010OESTE(2009,"OESTE",
			new ListaEquipos[] {ListaEquipos.LOSANGELESLAKERS,ListaEquipos.DALLASMAVERICKS,ListaEquipos.PHOENIXSUNS,ListaEquipos.DENVERNUGGETS,ListaEquipos.UTAHJAZZ,
								ListaEquipos.PORTLANDTRAILBLAZERS,ListaEquipos.SANANTONIOSPURS,ListaEquipos.OKLAHOMACITYTHUNDER,ListaEquipos.HOUSTONROCKETS,ListaEquipos.MEMPHISGRIZZLIES,
								ListaEquipos.NEWORLEANSHORNETS,ListaEquipos.LOSANGELESCLIPPERS,ListaEquipos.GOLDENSTATEWARRIORS,ListaEquipos.SACRAMENTOKINGS,ListaEquipos.MINNESOTATIMBERWOLVES}),
	
	
	SEASON20102011ESTE(2010,"ESTE",
			new ListaEquipos[] {ListaEquipos.CHICAGOBULLS,ListaEquipos.MIAMIHEAT,ListaEquipos.BOSTONCELTICS,ListaEquipos.ORLANDOMAGIC,ListaEquipos.ATLANTAHAWKS,
								ListaEquipos.NEWYORKKNICKS,ListaEquipos.PHILADELPHIA76ERS,ListaEquipos.INDIANAPACERS,ListaEquipos.MILWAUKEEBUCKS,ListaEquipos.CHARLOTTEBOBCATS,
								ListaEquipos.DETROITPISTONS,ListaEquipos.NEWJERSEYNETS,ListaEquipos.WASHINGTONWIZARDS,ListaEquipos.TORONTORAPTORS,ListaEquipos.CLEVELANDCAVALIERS}),
	
	
	SEASON20102011OESTE(2010,"OESTE",
			new ListaEquipos[] {ListaEquipos.SANANTONIOSPURS,ListaEquipos.LOSANGELESLAKERS,ListaEquipos.DALLASMAVERICKS,ListaEquipos.OKLAHOMACITYTHUNDER,ListaEquipos.DENVERNUGGETS,
								ListaEquipos.PORTLANDTRAILBLAZERS,ListaEquipos.NEWORLEANSHORNETS,ListaEquipos.MEMPHISGRIZZLIES,ListaEquipos.HOUSTONROCKETS,ListaEquipos.PHOENIXSUNS,
								ListaEquipos.UTAHJAZZ,ListaEquipos.GOLDENSTATEWARRIORS,ListaEquipos.LOSANGELESCLIPPERS,ListaEquipos.SACRAMENTOKINGS,ListaEquipos.MINNESOTATIMBERWOLVES}),
	
	
	SEASON20112012ESTE(2011,"ESTE",
			new ListaEquipos[] {ListaEquipos.CHICAGOBULLS,ListaEquipos.MIAMIHEAT,ListaEquipos.INDIANAPACERS,ListaEquipos.BOSTONCELTICS,ListaEquipos.ATLANTAHAWKS,
								ListaEquipos.ORLANDOMAGIC,ListaEquipos.NEWYORKKNICKS,ListaEquipos.PHILADELPHIA76ERS,ListaEquipos.MILWAUKEEBUCKS,ListaEquipos.DETROITPISTONS,
								ListaEquipos.TORONTORAPTORS,ListaEquipos.NEWJERSEYNETS,ListaEquipos.CLEVELANDCAVALIERS,ListaEquipos.WASHINGTONWIZARDS,ListaEquipos.CHARLOTTEBOBCATS}),
	
	
	SEASON20112012OESTE(2011,"OESTE",
			new ListaEquipos[] {ListaEquipos.SANANTONIOSPURS,ListaEquipos.OKLAHOMACITYTHUNDER,ListaEquipos.LOSANGELESLAKERS,ListaEquipos.MEMPHISGRIZZLIES,ListaEquipos.LOSANGELESCLIPPERS,
								ListaEquipos.DENVERNUGGETS,ListaEquipos.DALLASMAVERICKS,ListaEquipos.UTAHJAZZ,ListaEquipos.HOUSTONROCKETS,ListaEquipos.PHOENIXSUNS,
								ListaEquipos.PORTLANDTRAILBLAZERS,ListaEquipos.MINNESOTATIMBERWOLVES,ListaEquipos.GOLDENSTATEWARRIORS,ListaEquipos.SACRAMENTOKINGS,ListaEquipos.NEWORLEANSHORNETS}),
	
	
	SEASON20122013ESTE(2012,"ESTE",
			new ListaEquipos[] {ListaEquipos.MIAMIHEAT,ListaEquipos.NEWYORKKNICKS,ListaEquipos.INDIANAPACERS,ListaEquipos.BROOKLYNNETS,ListaEquipos.CHICAGOBULLS,
								ListaEquipos.ATLANTAHAWKS,ListaEquipos.BOSTONCELTICS,ListaEquipos.MILWAUKEEBUCKS,ListaEquipos.PHILADELPHIA76ERS,ListaEquipos.TORONTORAPTORS,
								ListaEquipos.DETROITPISTONS,ListaEquipos.WASHINGTONWIZARDS,ListaEquipos.CLEVELANDCAVALIERS,ListaEquipos.CHARLOTTEBOBCATS,ListaEquipos.ORLANDOMAGIC}),
	
	
	SEASON20122013OESTE(2012,"OESTE",
			new ListaEquipos[] {ListaEquipos.OKLAHOMACITYTHUNDER,ListaEquipos.SANANTONIOSPURS,ListaEquipos.DENVERNUGGETS,ListaEquipos.LOSANGELESCLIPPERS,ListaEquipos.MEMPHISGRIZZLIES,
								ListaEquipos.GOLDENSTATEWARRIORS,ListaEquipos.LOSANGELESLAKERS,ListaEquipos.HOUSTONROCKETS,ListaEquipos.UTAHJAZZ,ListaEquipos.DALLASMAVERICKS,
								ListaEquipos.PORTLANDTRAILBLAZERS,ListaEquipos.MINNESOTATIMBERWOLVES,ListaEquipos.SACRAMENTOKINGS,ListaEquipos.NEWORLEANSHORNETS,ListaEquipos.PHOENIXSUNS}),
	
	
	SEASON20132014ESTE(2013,"ESTE",
			new ListaEquipos[] {ListaEquipos.INDIANAPACERS,ListaEquipos.MIAMIHEAT,ListaEquipos.TORONTORAPTORS,ListaEquipos.CHICAGOBULLS,ListaEquipos.WASHINGTONWIZARDS,
								ListaEquipos.BROOKLYNNETS,ListaEquipos.CHARLOTTEBOBCATS,ListaEquipos.ATLANTAHAWKS,ListaEquipos.NEWYORKKNICKS,ListaEquipos.CLEVELANDCAVALIERS,
								ListaEquipos.DETROITPISTONS,ListaEquipos.BOSTONCELTICS,ListaEquipos.ORLANDOMAGIC,ListaEquipos.PHILADELPHIA76ERS,ListaEquipos.MILWAUKEEBUCKS}),
	
	
	SEASON20132014OESTE(2013,"OESTE",
			new ListaEquipos[] {ListaEquipos.SANANTONIOSPURS,ListaEquipos.OKLAHOMACITYTHUNDER,ListaEquipos.LOSANGELESCLIPPERS,ListaEquipos.HOUSTONROCKETS,ListaEquipos.PORTLANDTRAILBLAZERS,
								ListaEquipos.GOLDENSTATEWARRIORS,ListaEquipos.MEMPHISGRIZZLIES,ListaEquipos.DALLASMAVERICKS,ListaEquipos.PHOENIXSUNS,ListaEquipos.MINNESOTATIMBERWOLVES,
								ListaEquipos.DENVERNUGGETS,ListaEquipos.NEWORLEANSPELICANS,ListaEquipos.SACRAMENTOKINGS,ListaEquipos.LOSANGELESLAKERS,ListaEquipos.UTAHJAZZ}),
	
	
	SEASON20142015ESTE(2014,"ESTE",
			new ListaEquipos[] {ListaEquipos.ATLANTAHAWKS,ListaEquipos.CLEVELANDCAVALIERS,ListaEquipos.CHICAGOBULLS,ListaEquipos.TORONTORAPTORS,ListaEquipos.WASHINGTONWIZARDS,
								ListaEquipos.MILWAUKEEBUCKS,ListaEquipos.BOSTONCELTICS,ListaEquipos.BROOKLYNNETS,ListaEquipos.INDIANAPACERS,ListaEquipos.MIAMIHEAT,
								ListaEquipos.CHARLOTTEHORNETS,ListaEquipos.DETROITPISTONS,ListaEquipos.ORLANDOMAGIC,ListaEquipos.PHILADELPHIA76ERS,ListaEquipos.NEWYORKKNICKS}),
	
	
	SEASON20142015OESTE(2014,"OESTE",
			new ListaEquipos[] {ListaEquipos.GOLDENSTATEWARRIORS,ListaEquipos.HOUSTONROCKETS,ListaEquipos.LOSANGELESCLIPPERS,ListaEquipos.PORTLANDTRAILBLAZERS,ListaEquipos.MEMPHISGRIZZLIES,
								ListaEquipos.SANANTONIOSPURS,ListaEquipos.DALLASMAVERICKS,ListaEquipos.NEWORLEANSPELICANS,ListaEquipos.OKLAHOMACITYTHUNDER,ListaEquipos.PHOENIXSUNS,
								ListaEquipos.UTAHJAZZ,ListaEquipos.DENVERNUGGETS,ListaEquipos.SACRAMENTOKINGS,ListaEquipos.LOSANGELESLAKERS,ListaEquipos.MINNESOTATIMBERWOLVES}),
	
	
	SEASON20152016ESTE(2015,"ESTE",
			new ListaEquipos[] {ListaEquipos.CLEVELANDCAVALIERS,ListaEquipos.TORONTORAPTORS,ListaEquipos.MIAMIHEAT,ListaEquipos.ATLANTAHAWKS,ListaEquipos.BOSTONCELTICS,
								ListaEquipos.CHARLOTTEHORNETS,ListaEquipos.INDIANAPACERS,ListaEquipos.DETROITPISTONS,ListaEquipos.CHICAGOBULLS,ListaEquipos.WASHINGTONWIZARDS,
								ListaEquipos.ORLANDOMAGIC,ListaEquipos.MILWAUKEEBUCKS,ListaEquipos.NEWYORKKNICKS,ListaEquipos.BROOKLYNNETS,ListaEquipos.PHILADELPHIA76ERS}),
	
	
	SEASON20152016OESTE(2015,"OESTE",
			new ListaEquipos[] {ListaEquipos.GOLDENSTATEWARRIORS,ListaEquipos.SANANTONIOSPURS,ListaEquipos.OKLAHOMACITYTHUNDER,ListaEquipos.LOSANGELESCLIPPERS,ListaEquipos.PORTLANDTRAILBLAZERS,
								ListaEquipos.DALLASMAVERICKS,ListaEquipos.MEMPHISGRIZZLIES,ListaEquipos.HOUSTONROCKETS,ListaEquipos.UTAHJAZZ,ListaEquipos.SACRAMENTOKINGS,
								ListaEquipos.DENVERNUGGETS,ListaEquipos.NEWORLEANSPELICANS,ListaEquipos.MINNESOTATIMBERWOLVES,ListaEquipos.PHOENIXSUNS,ListaEquipos.LOSANGELESLAKERS}),
	
	
	SEASON20162017ESTE(2016,"ESTE",
			new ListaEquipos[] {ListaEquipos.BOSTONCELTICS,ListaEquipos.CLEVELANDCAVALIERS,ListaEquipos.TORONTORAPTORS,ListaEquipos.WASHINGTONWIZARDS,ListaEquipos.ATLANTAHAWKS,
								ListaEquipos.MILWAUKEEBUCKS,ListaEquipos.INDIANAPACERS,ListaEquipos.CHICAGOBULLS,ListaEquipos.MIAMIHEAT,ListaEquipos.DETROITPISTONS,
								ListaEquipos.CHARLOTTEHORNETS,ListaEquipos.NEWYORKKNICKS,ListaEquipos.ORLANDOMAGIC,ListaEquipos.PHILADELPHIA76ERS,ListaEquipos.BROOKLYNNETS}),
	
	
	SEASON20162017OESTE(2016,"OESTE",
			new ListaEquipos[] {ListaEquipos.GOLDENSTATEWARRIORS,ListaEquipos.SANANTONIOSPURS,ListaEquipos.HOUSTONROCKETS,ListaEquipos.LOSANGELESCLIPPERS,ListaEquipos.UTAHJAZZ,
								ListaEquipos.OKLAHOMACITYTHUNDER,ListaEquipos.MEMPHISGRIZZLIES,ListaEquipos.PORTLANDTRAILBLAZERS,ListaEquipos.DENVERNUGGETS,ListaEquipos.NEWORLEANSPELICANS,
								ListaEquipos.DALLASMAVERICKS,ListaEquipos.SACRAMENTOKINGS,ListaEquipos.MINNESOTATIMBERWOLVES,ListaEquipos.LOSANGELESLAKERS,ListaEquipos.PHOENIXSUNS}),
	
	
	SEASON20172018ESTE(2017,"ESTE",
			new ListaEquipos[] {ListaEquipos.TORONTORAPTORS,ListaEquipos.BOSTONCELTICS,ListaEquipos.PHILADELPHIA76ERS,ListaEquipos.CLEVELANDCAVALIERS,ListaEquipos.INDIANAPACERS,
								ListaEquipos.MIAMIHEAT,ListaEquipos.MILWAUKEEBUCKS,ListaEquipos.WASHINGTONWIZARDS,ListaEquipos.DETROITPISTONS,ListaEquipos.CHARLOTTEHORNETS,
								ListaEquipos.NEWYORKKNICKS,ListaEquipos.BROOKLYNNETS,ListaEquipos.CHICAGOBULLS,ListaEquipos.ORLANDOMAGIC,ListaEquipos.ATLANTAHAWKS}),
	
	
	SEASON20172018OESTE(2017,"OESTE",
			new ListaEquipos[] {ListaEquipos.HOUSTONROCKETS,ListaEquipos.GOLDENSTATEWARRIORS,ListaEquipos.PORTLANDTRAILBLAZERS,ListaEquipos.OKLAHOMACITYTHUNDER,ListaEquipos.UTAHJAZZ,
								ListaEquipos.NEWORLEANSPELICANS,ListaEquipos.SANANTONIOSPURS,ListaEquipos.MINNESOTATIMBERWOLVES,ListaEquipos.DENVERNUGGETS,ListaEquipos.LOSANGELESCLIPPERS,
								ListaEquipos.LOSANGELESLAKERS,ListaEquipos.SACRAMENTOKINGS,ListaEquipos.DALLASMAVERICKS,ListaEquipos.MEMPHISGRIZZLIES,ListaEquipos.PHOENIXSUNS}),
	
	
	SEASON20182019ESTE(2018,"ESTE",
			new ListaEquipos[] {ListaEquipos.MILWAUKEEBUCKS,ListaEquipos.TORONTORAPTORS,ListaEquipos.PHILADELPHIA76ERS,ListaEquipos.BOSTONCELTICS,ListaEquipos.INDIANAPACERS,
								ListaEquipos.BROOKLYNNETS,ListaEquipos.ORLANDOMAGIC,ListaEquipos.DETROITPISTONS,ListaEquipos.CHARLOTTEHORNETS,ListaEquipos.MIAMIHEAT,
								ListaEquipos.WASHINGTONWIZARDS,ListaEquipos.ATLANTAHAWKS,ListaEquipos.CHICAGOBULLS,ListaEquipos.CLEVELANDCAVALIERS,ListaEquipos.NEWYORKKNICKS}),
	
	
	SEASON20182019OESTE(2018,"OESTE",
			new ListaEquipos[] {ListaEquipos.GOLDENSTATEWARRIORS,ListaEquipos.DENVERNUGGETS,ListaEquipos.PORTLANDTRAILBLAZERS,ListaEquipos.HOUSTONROCKETS,ListaEquipos.UTAHJAZZ,
								ListaEquipos.OKLAHOMACITYTHUNDER,ListaEquipos.SANANTONIOSPURS,ListaEquipos.LOSANGELESCLIPPERS,ListaEquipos.SACRAMENTOKINGS,ListaEquipos.LOSANGELESLAKERS,
								ListaEquipos.MINNESOTATIMBERWOLVES,ListaEquipos.MEMPHISGRIZZLIES,ListaEquipos.NEWORLEANSPELICANS,ListaEquipos.DALLASMAVERICKS,ListaEquipos.PHOENIXSUNS}),
	
	
	SEASON20192020ESTE(2019,"ESTE",
			new ListaEquipos[] {ListaEquipos.MILWAUKEEBUCKS,ListaEquipos.TORONTORAPTORS,ListaEquipos.BOSTONCELTICS,ListaEquipos.INDIANAPACERS,ListaEquipos.MIAMIHEAT,
								ListaEquipos.PHILADELPHIA76ERS,ListaEquipos.BROOKLYNNETS,ListaEquipos.ORLANDOMAGIC,ListaEquipos.WASHINGTONWIZARDS,ListaEquipos.CHARLOTTEHORNETS,
								ListaEquipos.CHICAGOBULLS,ListaEquipos.NEWYORKKNICKS,ListaEquipos.DETROITPISTONS,ListaEquipos.ATLANTAHAWKS,ListaEquipos.CLEVELANDCAVALIERS}),
	
	
	SEASON20192020OESTE(2019,"OESTE",
			new ListaEquipos[] {ListaEquipos.LOSANGELESLAKERS,ListaEquipos.LOSANGELESCLIPPERS,ListaEquipos.DENVERNUGGETS,ListaEquipos.HOUSTONROCKETS,ListaEquipos.OKLAHOMACITYTHUNDER,
								ListaEquipos.UTAHJAZZ,ListaEquipos.DALLASMAVERICKS,ListaEquipos.PORTLANDTRAILBLAZERS,ListaEquipos.MEMPHISGRIZZLIES,ListaEquipos.PHOENIXSUNS,
								ListaEquipos.SANANTONIOSPURS,ListaEquipos.SACRAMENTOKINGS,ListaEquipos.NEWORLEANSPELICANS,ListaEquipos.MINNESOTATIMBERWOLVES,ListaEquipos.GOLDENSTATEWARRIORS}),
	
	
	SEASON20202021ESTE(2020,"ESTE",
			new ListaEquipos[] {ListaEquipos.PHILADELPHIA76ERS,ListaEquipos.BROOKLYNNETS,ListaEquipos.MILWAUKEEBUCKS,ListaEquipos.NEWYORKKNICKS,ListaEquipos.ATLANTAHAWKS,
								ListaEquipos.MIAMIHEAT,ListaEquipos.BOSTONCELTICS,ListaEquipos.WASHINGTONWIZARDS,ListaEquipos.INDIANAPACERS,ListaEquipos.CHARLOTTEHORNETS,
								ListaEquipos.CHICAGOBULLS,ListaEquipos.TORONTORAPTORS,ListaEquipos.CLEVELANDCAVALIERS,ListaEquipos.ORLANDOMAGIC,ListaEquipos.DETROITPISTONS}),
	
	
	SEASON20202021OESTE(2020,"OESTE",
			new ListaEquipos[] {ListaEquipos.UTAHJAZZ,ListaEquipos.PHOENIXSUNS,ListaEquipos.DENVERNUGGETS,ListaEquipos.LOSANGELESCLIPPERS,ListaEquipos.DALLASMAVERICKS,
								ListaEquipos.PORTLANDTRAILBLAZERS,ListaEquipos.LOSANGELESLAKERS,ListaEquipos.MEMPHISGRIZZLIES,ListaEquipos.GOLDENSTATEWARRIORS,ListaEquipos.SANANTONIOSPURS,
								ListaEquipos.NEWORLEANSPELICANS,ListaEquipos.SACRAMENTOKINGS,ListaEquipos.MINNESOTATIMBERWOLVES,ListaEquipos.OKLAHOMACITYTHUNDER,ListaEquipos.HOUSTONROCKETS}),
	
	
	SEASON20212022ESTE(2021,"ESTE",
			new ListaEquipos[] {ListaEquipos.MIAMIHEAT,ListaEquipos.BOSTONCELTICS,ListaEquipos.MILWAUKEEBUCKS,ListaEquipos.PHILADELPHIA76ERS,ListaEquipos.TORONTORAPTORS,
								ListaEquipos.CHICAGOBULLS,ListaEquipos.BROOKLYNNETS,ListaEquipos.ATLANTAHAWKS,ListaEquipos.CLEVELANDCAVALIERS,ListaEquipos.CHARLOTTEHORNETS,
								ListaEquipos.NEWYORKKNICKS,ListaEquipos.WASHINGTONWIZARDS,ListaEquipos.INDIANAPACERS,ListaEquipos.DETROITPISTONS,ListaEquipos.ORLANDOMAGIC}),
	
	
	SEASON20212022OESTE(2021,"OESTE",
			new ListaEquipos[] {ListaEquipos.PHOENIXSUNS,ListaEquipos.MEMPHISGRIZZLIES,ListaEquipos.GOLDENSTATEWARRIORS,ListaEquipos.DALLASMAVERICKS,ListaEquipos.UTAHJAZZ,
								ListaEquipos.DENVERNUGGETS,ListaEquipos.MINNESOTATIMBERWOLVES,ListaEquipos.NEWORLEANSPELICANS,ListaEquipos.LOSANGELESCLIPPERS,ListaEquipos.SANANTONIOSPURS,
								ListaEquipos.LOSANGELESLAKERS,ListaEquipos.SACRAMENTOKINGS,ListaEquipos.PORTLANDTRAILBLAZERS,ListaEquipos.OKLAHOMACITYTHUNDER,ListaEquipos.HOUSTONROCKETS}),
	
	
	SEASON20222023ESTE(2022,"ESTE",
			new ListaEquipos[] {ListaEquipos.MILWAUKEEBUCKS,ListaEquipos.BOSTONCELTICS,ListaEquipos.PHILADELPHIA76ERS,ListaEquipos.CLEVELANDCAVALIERS,ListaEquipos.NEWYORKKNICKS,
								ListaEquipos.BROOKLYNNETS,ListaEquipos.ATLANTAHAWKS,ListaEquipos.MIAMIHEAT,ListaEquipos.TORONTORAPTORS,ListaEquipos.CHICAGOBULLS,
								ListaEquipos.INDIANAPACERS,ListaEquipos.WASHINGTONWIZARDS,ListaEquipos.ORLANDOMAGIC,ListaEquipos.CHARLOTTEHORNETS,ListaEquipos.DETROITPISTONS}),
	
	
	SEASON20222023OESTE(2022,"OESTE",
			new ListaEquipos[] {ListaEquipos.DENVERNUGGETS,ListaEquipos.MEMPHISGRIZZLIES,ListaEquipos.SACRAMENTOKINGS,ListaEquipos.PHOENIXSUNS,ListaEquipos.LOSANGELESCLIPPERS,
								ListaEquipos.GOLDENSTATEWARRIORS,ListaEquipos.LOSANGELESLAKERS,ListaEquipos.MINNESOTATIMBERWOLVES,ListaEquipos.NEWORLEANSPELICANS,ListaEquipos.OKLAHOMACITYTHUNDER,
								ListaEquipos.DALLASMAVERICKS,ListaEquipos.UTAHJAZZ,ListaEquipos.PORTLANDTRAILBLAZERS,ListaEquipos.HOUSTONROCKETS,ListaEquipos.SANANTONIOSPURS});
	
	
	
	private final int season;
	private final String conferencia;
	private final ListaEquipos[] clasificacion;
	
	private ListaClasificaciones(int season, String conferencia, ListaEquipos[] clasificacion) {
		this.season=season;
		this.conferencia=conferencia;
		this.clasificacion=clasificacion;
	}
	
	public int getSeason() {
		return season;
	}
	
	public String getConferencia() {
		return conferencia;
	}
	
	public ListaEquipos[] getClasificacion() {
		return clasificacion;
	}
	
	public static ListaEquipos[] findClasificacionByYearConferencia(int season, String conferencia) {
		for(ListaClasificaciones clasificacion : ListaClasificaciones.values()) {
			if(clasificacion.getSeason()==season && clasificacion.getConferencia().equals(conferencia)) {
				return clasificacion.clasificacion;
			}
		}
		return null;
	}

}
